
/*

 includes/cctld.hpp
   
   Copyright (c) 2003-2008 by Philippe Bourcier
   
   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 2, or (at your option)
   any later version.
   
   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.
   
   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software Foundation,
   Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.

*/

string get_countryname(string tld) {
tld=php_strtoupper(tld);
if(tld=="AC") return "Ascension Island";
if(tld=="AD") return "Andorra";
if(tld=="AE") return "United Arab Emirates";
if(tld=="AF") return "Afghanistan";
if(tld=="AG") return "Antigua and Barbuda";
if(tld=="AI") return "Anguilla";
if(tld=="AL") return "Albania";
if(tld=="AM") return "Armenia";
if(tld=="AN") return "Netherlands Antilles";
if(tld=="AO") return "Angola";
if(tld=="AQ") return "Antarctica";
if(tld=="AR") return "Argentina";
if(tld=="AS") return "American Samoa";
if(tld=="AT") return "Austria";
if(tld=="AU") return "Australia";
if(tld=="AW") return "Aruba";
if(tld=="AX") return "Aland Islands";
if(tld=="AZ") return "Azerbaijan";
if(tld=="BA") return "Bosnia and Herzegovina";
if(tld=="BB") return "Barbados";
if(tld=="BD") return "Bangladesh";
if(tld=="BE") return "Belgium";
if(tld=="BF") return "Burkina Faso";
if(tld=="BG") return "Bulgaria";
if(tld=="BH") return "Bahrain";
if(tld=="BI") return "Burundi";
if(tld=="BJ") return "Benin";
if(tld=="BL") return "Saint Barthelemy";
if(tld=="BM") return "Bermuda";
if(tld=="BN") return "Brunei Darussalam";
if(tld=="BO") return "Bolivia";
if(tld=="BR") return "Brazil";
if(tld=="BS") return "Bahamas";
if(tld=="BT") return "Bhutan";
if(tld=="BV") return "Bouvet Island";
if(tld=="BW") return "Botswana";
if(tld=="BY") return "Belarus";
if(tld=="BZ") return "Belize";
if(tld=="CA") return "Canada";
if(tld=="CC") return "Cocos";
if(tld=="CD") return "The Democratic Republic of the Congo";
if(tld=="CF") return "Central African Republic";
if(tld=="CG") return "Congo";
if(tld=="CH") return "Switzerland";
if(tld=="CI") return "Cote d'Ivoire";
if(tld=="CK") return "Cook Islands";
if(tld=="CL") return "Chile";
if(tld=="CM") return "Cameroon";
if(tld=="CN") return "China";
if(tld=="CO") return "Colombia";
if(tld=="CR") return "Costa Rica";
if(tld=="CU") return "Cuba";
if(tld=="CV") return "Cape Verde";
if(tld=="CX") return "Christmas Island";
if(tld=="CY") return "Cyprus";
if(tld=="CZ") return "Czech Republic";
if(tld=="DE") return "Germany";
if(tld=="DJ") return "Djibouti";
if(tld=="DK") return "Denmark";
if(tld=="DM") return "Dominica";
if(tld=="DO") return "Dominican Republic";
if(tld=="DZ") return "Algeria";
if(tld=="EC") return "Ecuador";
if(tld=="EE") return "Estonia";
if(tld=="EG") return "Egypt";
if(tld=="EH") return "Western Sahara";
if(tld=="ER") return "Eritrea";
if(tld=="ES") return "Spain";
if(tld=="ET") return "Ethiopia";
if(tld=="EU") return "European Union";
if(tld=="FI") return "Finland";
if(tld=="FJ") return "Fiji";
if(tld=="FK") return "Falkland Islands";
if(tld=="FM") return "Federated States of Micronesia";
if(tld=="FO") return "Faroe Islands";
if(tld=="FR") return "France";
if(tld=="GA") return "Gabon";
if(tld=="GB") return "United Kingdom";
if(tld=="GD") return "Grenada";
if(tld=="GE") return "Georgia";
if(tld=="GF") return "French Guiana";
if(tld=="GG") return "Guernsey";
if(tld=="GH") return "Ghana";
if(tld=="GI") return "Gibraltar";
if(tld=="GL") return "Greenland";
if(tld=="GM") return "Gambia";
if(tld=="GN") return "Guinea";
if(tld=="GP") return "Guadeloupe";
if(tld=="GQ") return "Equatorial Guinea";
if(tld=="GR") return "Greece";
if(tld=="GS") return "South Georgia and the South Sandwich Islands";
if(tld=="GT") return "Guatemala";
if(tld=="GU") return "Guam";
if(tld=="GW") return "Guinea-Bissau";
if(tld=="GY") return "Guyana";
if(tld=="HK") return "Hong Kong";
if(tld=="HM") return "Heard Island and McDonald Islands";
if(tld=="HN") return "Honduras";
if(tld=="HR") return "Croatia";
if(tld=="HT") return "Haiti";
if(tld=="HU") return "Hungary";
if(tld=="ID") return "Indonesia";
if(tld=="IE") return "Ireland";
if(tld=="IL") return "Israel";
if(tld=="IM") return "Isle of Man";
if(tld=="IN") return "India";
if(tld=="IO") return "British Indian Ocean Territory";
if(tld=="IQ") return "Iraq";
if(tld=="IR") return "Islamic Republic of Iran";
if(tld=="IS") return "Iceland";
if(tld=="IT") return "Italy";
if(tld=="JE") return "Jersey";
if(tld=="JM") return "Jamaica";
if(tld=="JO") return "Jordan";
if(tld=="JP") return "Japan";
if(tld=="KE") return "Kenya";
if(tld=="KG") return "Kyrgyzstan";
if(tld=="KH") return "Cambodia";
if(tld=="KI") return "Kiribati";
if(tld=="KM") return "Comoros";
if(tld=="KN") return "Saint Kitts and Nevis";
if(tld=="KP") return "Democratic People's Republic of Korea";
if(tld=="KR") return "Republic of Korea";
if(tld=="KW") return "Kuwait";
if(tld=="KY") return "Cayman Islands";
if(tld=="KZ") return "Kazakhstan";
if(tld=="LA") return "Lao People's Democratic Republic";
if(tld=="LB") return "Lebanon";
if(tld=="LC") return "Saint Lucia";
if(tld=="LI") return "Liechtenstein";
if(tld=="LK") return "Sri Lanka";
if(tld=="LR") return "Liberia";
if(tld=="LS") return "Lesotho";
if(tld=="LT") return "Lithuania";
if(tld=="LU") return "Luxembourg";
if(tld=="LV") return "Latvia";
if(tld=="LY") return "Libyan Arab Jamahiriya";
if(tld=="MA") return "Morocco";
if(tld=="MC") return "Monaco";
if(tld=="MD") return "Moldova";
if(tld=="ME") return "Montenegro";
if(tld=="MF") return "Saint Martin";
if(tld=="MG") return "Madagascar";
if(tld=="MH") return "Marshall Islands";
if(tld=="MK") return "The Former Yugoslav Republic of Macedonia";
if(tld=="ML") return "Mali";
if(tld=="MM") return "Myanmar";
if(tld=="MN") return "Mongolia";
if(tld=="MO") return "Macao";
if(tld=="MP") return "Northern Mariana Islands";
if(tld=="MQ") return "Martinique";
if(tld=="MR") return "Mauritania";
if(tld=="MS") return "Montserrat";
if(tld=="MT") return "Malta";
if(tld=="MU") return "Mauritius";
if(tld=="MV") return "Maldives";
if(tld=="MW") return "Malawi";
if(tld=="MX") return "Mexico";
if(tld=="MY") return "Malaysia";
if(tld=="MZ") return "Mozambique";
if(tld=="NA") return "Namibia";
if(tld=="NC") return "New Caledonia";
if(tld=="NE") return "Niger";
if(tld=="NF") return "Norfolk Island";
if(tld=="NG") return "Nigeria";
if(tld=="NI") return "Nicaragua";
if(tld=="NL") return "Netherlands";
if(tld=="NO") return "Norway";
if(tld=="NP") return "Nepal";
if(tld=="NR") return "Nauru";
if(tld=="NU") return "Niue";
if(tld=="NZ") return "New Zealand";
if(tld=="OM") return "Oman";
if(tld=="PA") return "Panama";
if(tld=="PE") return "Peru";
if(tld=="PF") return "French Polynesia";
if(tld=="PG") return "Papua New Guinea";
if(tld=="PH") return "Philippines";
if(tld=="PK") return "Pakistan";
if(tld=="PL") return "Poland";
if(tld=="PM") return "Saint Pierre and Miquelon";
if(tld=="PN") return "Pitcairn";
if(tld=="PR") return "Puerto Rico";
if(tld=="PS") return "Occupied Palestinian Territory";
if(tld=="PT") return "Portugal";
if(tld=="PW") return "Palau";
if(tld=="PY") return "Paraguay";
if(tld=="QA") return "Qatar";
if(tld=="RE") return "Reunion";
if(tld=="RO") return "Romania";
if(tld=="RS") return "Serbia";
if(tld=="RU") return "Russian Federation";
if(tld=="RW") return "Rwanda";
if(tld=="SA") return "Saudi Arabia";
if(tld=="SB") return "Solomon Islands";
if(tld=="SC") return "Seychelles";
if(tld=="SD") return "Sudan";
if(tld=="SE") return "Sweden";
if(tld=="SG") return "Singapore";
if(tld=="SH") return "Saint Helena";
if(tld=="SI") return "Slovenia";
if(tld=="SJ") return "Svalbard and Jan Mayen";
if(tld=="SK") return "Slovakia";
if(tld=="SL") return "Sierra Leone";
if(tld=="SM") return "San Marino";
if(tld=="SN") return "Senegal";
if(tld=="SO") return "Somalia";
if(tld=="SR") return "Suriname";
if(tld=="ST") return "Sao Tome and Principe";
if(tld=="SU") return "Soviet Union";
if(tld=="SV") return "El Salvador";
if(tld=="SY") return "Syrian Arab Republic";
if(tld=="SZ") return "Swaziland";
if(tld=="TC") return "Turks and Caicos Islands";
if(tld=="TD") return "Chad";
if(tld=="TF") return "French Southern Territories";
if(tld=="TG") return "Togo";
if(tld=="TH") return "Thailand";
if(tld=="TJ") return "Tajikistan";
if(tld=="TK") return "Tokelau";
if(tld=="TL") return "Timor-Leste";
if(tld=="TM") return "Turkmenistan";
if(tld=="TN") return "Tunisia";
if(tld=="TO") return "Tonga";
if(tld=="TP") return "Portuguese Timor";
if(tld=="TR") return "Turkey";
if(tld=="TT") return "Trinidad and Tobago";
if(tld=="TV") return "Tuvalu";
if(tld=="TW") return "Taiwan";
if(tld=="TZ") return "United Republic of Tanzania";
if(tld=="UA") return "Ukraine";
if(tld=="UG") return "Uganda";
if(tld=="UK") return "United Kingdom";
if(tld=="UM") return "United States Minor Outlying Islands";
if(tld=="US") return "United States";
if(tld=="UY") return "Uruguay";
if(tld=="UZ") return "Uzbekistan";
if(tld=="VA") return "Holy See";
if(tld=="VC") return "Saint Vincent and the Grenadines";
if(tld=="VE") return "Venezuela";
if(tld=="VG") return "British Virgin Islands";
if(tld=="VI") return "U.S. Virgin Islands";
if(tld=="VN") return "Viet Nam";
if(tld=="VU") return "Vanuatu";
if(tld=="WF") return "Wallis and Futuna";
if(tld=="WS") return "Samoa";
if(tld=="YE") return "Yemen";
if(tld=="YT") return "Mayotte";
if(tld=="YU") return "Yugoslavia";
if(tld=="ZA") return "South Africa";
if(tld=="ZM") return "Zambia";
if(tld=="ZW") return "Zimbabwe";
return "Not Found";
}

